### ISSUE TITLE
Set up a new user guide

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#10]
We need to deploy a help site users that would be deployed alongside the main website. We should look into libraries and technologies to help us build this from Markdown for example. It should be possible to include screenshots of the site to help guide users.

**Acceptance Criteria**

- [x] A help site for the main website exists
- [x] It can be viewed alongside with the main site
- [x] It's possible to render screenshots in the user guide.

**Comment by andykitch** [comment]
To reach this help site, navigate to <base_url>/help, where <base_url> is the url of the homepage

**Comment by colin-turner-cg** [comment]
All Acceptance Criteria met, Test Case TC-10 created.

1) A help site for the main website exists - accessible at http://localhost:1234/help/ but 404 error displayed if trailing slash omitted. Bug https://github.com/icipe-official/vectoratlas-software-code/issues/63 to fix redirect when trailing slash is not included.

2) It can be viewed alongside with the main site - see above

3) It's possible to render screenshots in the user guide - confirmed by visiting: http://localhost:1234/help/Uploading%20data/How%20to%20upload%20data
