### ISSUE TITLE
Filter occurrence data by area

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#101]
Allow users to filter the occurrence data on the map by selecting a polygon of data on the map.

**Acceptance criteria**:
- [x] Users can select an area of interest on the map using the points of a polygon.
- [x] The occurrence data should filter to just the points inside the polygon.

**Comment by Christopher-Sandbach** [comment]
Investigation complete. Should be implementation of the drawing tool

**Comment by colin-turner-cg** [comment]
When using the "select by area" tool the map correctly displays only those data points that lay inside the bounds drawn. However, when clicking the "Download filtered data" button all data, including data points outside of the bound, is included in the downloaded file.

**Comment by colin-turner-cg** [comment]
TC-7.3 now passes, the data file downloaded when clicking "Download filtered data" now only includes data from within the area drawn.
