### ISSUE TITLE
Create a secured upload page

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#102]
Create a page in the UI for users to upload data. This needs to be authenticated and authorised against the `is_uploader` role in the db.
This should include a simple form for uploading a csv file and choosing which data type is being uploaded (currently bionomics or occurrence). 
The UI should then post the file to the correct API endpoint (/ingest/uploadBionomics or /ingest/uploadOccurrence), sending with it the bearer token that is stored in the redux state.

Acceptance Criteria:
- [x] A page exists in the UI for users to upload data, accessible from the `Upload Data` button on the homepage
- [x] Only users with the `is_uploader` role can access the page

**Comment by ray-millward-tessella** [comment]
should include form for uploading csv
this should at least validate against correct required headers

**Comment by colin-turner-cg** [comment]
Closing now AC updated
