### ISSUE TITLE
Secure the API upload route

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#103]
Update the API uploading routes so they require an uploader role, several other API routes require roles so they can be used as an example. It should be a case of adding the auth decorator with an uploader role.

**Acceptance criteria**:
- [x] only uploaders can upload files to the upload routes
- [x] the API returns an unauthorised if a user does not have the uploader role.

**Comment by colin-turner-cg** [comment]
Tested by:
1) Getting a Bearer token using Redux in Chrome dev tools for a user with and without the "Uploader" role.
2) Sending an API request to add Occurrence and Bionomics data to the relevant endpoints:
With no Bearer token - `401 unauthorized` returned
With a Bearer token belonging to a user without the "Uploader" role - `403 Forbidden` returned
With a Bearer token belonging to a user with the "Uploader" role - `201 Created` returned
