### ISSUE TITLE
Update the map to show availble filters and wire in to marker route

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#107]
Depends on #106 being done first

Add filters for the properties outlined by Marianne to the map. Update the graphql query for map data to pass these filters to the api. 

The list of filters is country, species, date ranges, larval/adult data, control (y/n), season (rain/dry)

**Acceptance criteria**:
- [x] Users can filter data in the map view based on the properties outlined by Marianne.
- [x] The markers on the map correspond to the filtered data.

**Comment by Christopher-Sandbach** [comment]
Handed story over to Ray this afternoon. The main points covered:

- filterToggle test needs fixing. Button can be clicked once and will dispatch the correct action, but any subsequent press seems inoperative.

- Filter was tested during handover and is functional, but to evaluate it properly we need to verify that the test data is accurate (ie// Point in Egypt labelled as Sudan) and ideally main should merge in to take advantage of Andrew's map reload updates. However, the merge mentioned in the latter did break the map page when attempted earlier on in the ticket. So, that is a separate investigation if that occurs again

- Currently the boolean filters are present in the mapSlice as [true, false, 'empty]. I think this will require review. Especially when considering how this will wire up following story #206.

- The use of : any within the changed files will be worth a bit of clean-up. It was used just to get something up and running if a type or interface was a little more complicated.

- Must implement a method to handle filter requests. If the filter is changed whilst points are still loading, it is rendered useless as the previous points will continue to load. Some sort of filterId or requestId

- We should also ask Marianne to consider the ICIPE graphic designer to create some filter icons for us. Aside from season they don't quite match the style of the website, nor are they completely relevant.

**Comment by ray-millward-tessella** [comment]
All filters including area with #101 now implemented.
