### ISSUE TITLE
Add download data button based on current view selection

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#108]
Add a new API route to download the data within the current map bounds and with the current filters to a csv file. The API should stream this data rather than trying to build the entire file in memory first in case the number of results is large.

This route should then be hooked up to a button on the map page.

**Acceptance criteria**
- [x] The user can download all of the vector data from their current filters as a csv file.
- [x] A developer review should check that the contents of the file are being streamed rather than built in one go.

**Comment by colin-turner-cg** [comment]
I've spoken to Ray about this story - currently the data downloaded isn't constrained to the map view. The AC needs adjusting or map filtering by area put in place.

**Comment by ray-millward-tessella** [comment]
I've updated the acceptance criteria as at the moment it doesn't make sense to filter on the location as this might change a lot and create a lot of extra load on the API. We need to work out what a sensible longer term plan is.
