### ISSUE TITLE
Add download everything button

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#109]
When the upload data route is called, trigger an update to build a new csv containing all of the data now in the database. Add a new route to the API to download this file. Update the download all button on the homepage to retrieve this file, it should just use the normal file download mechanism in the browser so this happens in the background.

**Acceptance criteria**:
- [x] Users can download all the vector data from the database as a csv.
- [x] The download includes new data after additional data is uploaded to the system (must go through upload, not directly into the db otherwise the new file building isn't triggered).

**Comment by Christopher-Sandbach** [comment]
Might have to consider what happens if someone is downloading the file at the same time as attempting update

**Comment by colin-turner-cg** [comment]
Test TC-4.1 added to STS

**Comment by colin-turner-cg** [comment]
@ray-millward-tessella @Christopher-Sandbach please be aware that only occurrence data is included in the csv download. 

I can see the ingest is being updated in my logs when I upload bionomics data but this isn't included in the csv.
`docker-api-1          |  New Ingest`
`docker-api-1          |    Last Ingest Time:  {`
`docker-api-1          |   ingestion: { ingestTime: '2022-10-21T13:24:37.009Z', isLocked: true }`
`docker-api-1          | }`
`docker-api-1          |    Current Ingest Time:  {`
`docker-api-1          |   ingestion: { ingestTime: '2022-10-21T13:24:38.227Z', isLocked: true }`
`docker-api-1          | }`


Ray has said that this will be clarified with Marianne and new stories created to include other data (if required).
