### ISSUE TITLE
Add tile caching to improve performance

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#111]
Add route caching to the nginx proxy for the tile server tiles to avoid on the fly calculation. Each call to the tile server causes it to calculate the tile needed for the request.

We should add caching to the nginx reverse proxy to cache calls to the /data/ route for pbf files and png files (or whatever file format is returned for the tiles). The cache time should be set to 1 hr for now to allow for updates to the model overlays if needed.

We should also add preloading to the map component in the UI https://openlayers.org/en/latest/examples/preload.html

**Acceptance criteria**:
- [x] Tiles (pbf and png files) have a cache-control header in the browser and a time to expire of 1hr.
- [x] The map component pre-loads tiles.

**Comment by colin-turner-cg** [comment]
AC met: 
1) png tile files have the header: `Cache-Control: max-age=3600`
2) At a high (high = zoomed in) zoom level map behavior when panning/adjusting zoom is similar to that here: https://openlayers.org/en/latest/examples/preload.html.
I've confirmed using my local log that the tileserver isn't called when performing panning actions at high zoom.
I can also see that the `X-Cache-Status` has the value `HIT` when loading the map in a different broswer.
