### ISSUE TITLE
Add versioning and feature flags for the website and api

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#12]
Both the website and api should get a version as part of their build based on the latest git tag and the current sha, e.g. 1.0.0-abc23g. These can potentially be different if the api and website are built independently - but equally a choice might be taken to always build both together to keep them in sync.

The website should load the api version information along with a series of feature flags from an api endpoint. We may only have an example feature flag for now.

**Acceptance Criteria**:

- [x] The website display a version based on the latest build's tag and sha.
- [x] The website displays the version of the api based on the api's latest build tag and sha.
- [x] The website loads feature flags from the api, an example feature flag can be used to disable something in the website.

**Comment by colin-turner-cg** [comment]
Feature flag functionality has been demonstrated to me by Andrew.

The website/api version is not being displayed to me, this is thought to be caused by using code from the temporary repo.

**Comment by colin-turner-cg** [comment]
I've confirmed that the website is now displaying the UI and API versions (on port 1234). Logging into the website redirects to port 3000, this causes the API version to be displayed as "Internal Server Error", being logged in and manually navigating to port 1234 will display the UI and API versions correctly.
