### ISSUE TITLE
Update the UI to display well on mobile devices

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#121]
The website currently renders okay on mobile devices, but more could be done to make it look nicer. Things to fix:

- Remove guttering when displayed on mobiles (is okay on tablets). This should fix the Team view:
![image](https://user-images.githubusercontent.com/32331816/192218860-8c04f4c5-e90c-48ae-8ba5-6313c4693740.png)
- Reduce font size when on mobile devices
- Fix navbar, making icon bigger and turning menu into hamburger

Acceptance Criteria:
- [x] The above issues are fixed for displaying the website on mobile devices, both in portrait and landscape mode
- [x] No changes to the website view on larger screens

**Comment by colin-turner-cg** [comment]
@andykitch @ray-millward-tessella @gituman The AC has been met on this story but I think maybe a new one could be created to tidy up the spacing of some elements on the page.

Portrait
![image](https://user-images.githubusercontent.com/109605071/203095692-8c40973a-4c05-4ec9-894c-41d11211d134.png)

Landscape
![image](https://user-images.githubusercontent.com/109605071/203095920-1a0a2c9a-fb27-4499-abdb-6c3616921fb0.png)
