### ISSUE TITLE
Create a docker build for the website and the api

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#13]
The website and api will need to run inside docker containers - we should create docker files for each of them. These only need to be for the final application at this point - it is unclear whether the build steps could get information about where the build fails inside the docker file so we'll extend these files later.

It's important that the docker files only install the production dependencies (not dev-dependencies) in order to reduce the size of the image. They should also be based off a small image (e.g. node-alpine) to improve performance.

**Acceptance Criteria**

- [x] A docker file exists, builds and runs for the website.
- [x] A docker file exists, builds and runs for the api
- [x] The base image should be a lightweight container unless a good technical reason is defined.

**Comment by colin-turner-cg** [comment]
All acceptance criteria has been in the following ways:
1) A docker file exists, builds and runs for the website.
2) A docker file exists, builds and runs for the api.
A docker-compose file for the website/api exists in the src/Docker folder. `docker-compose build` and `docker-compose up` run with no error.

3) The base image should be a lightweight container unless a good technical reason is defined.
Alpine is being used, which is the lightest version of Node that can be used.
