### ISSUE TITLE
Add test data to the source repository

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#131]
We need to have a source of test data that developers can use to populate their local systems with, this should be part of the code base and maintained whenever the data model changes and therefore the ingest changes.

**Acceptance criteria**:
- [x] Test data is included in the code repository
- [x] It can be ingested successfully into the database when running a development environment.
- [x] Instructions for loading the data are part of the SMG.

**Comment by colin-turner-cg** [comment]
All AC met:
1 - Test data is included in the code repository at: `src\Database\test_data`

2 - The test data has been ingested successfully into the database development environment with the following API commands using Postman:
`POST localhost:1234/vector-api/ingest/uploadBionomics`
`POST localhost:1234/vector-api/ingest/uploadOccurrence `

3 - Instructions for loading the data are included as part of the SMG at: `docs\SMG\10-working-with-database.md`

STS ref: `TC-2.3`
