### ISSUE TITLE
Investigate displaying the vector atlas logo on the map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#133]
We should investigate what options we have for displaying the logo on the map. It will also be important to investigate how the logo gets included in the download of the map image. For example, one option is to display the logo as a separate React component over the top of the map but then it is unclear how this gets included on the downloaded image (which is exported from the map canvas).

**Acceptance criteria**:
- [x] ~~The investigation is documented on this issue~~
- [x] ~~An ADR for the resulting decision has been created~~
- [x] New stories for implementation have been created.

**Comment by gituman** [comment]
Investigation was performed and a solution was found and implemented by Peter.

**Comment by colin-turner-cg** [comment]
@gituman @ray-millward-tessella are the documented investigation and ADR no longer required?

**Comment by andykitch** [comment]
@colin-turner-cg The solution was quite simple in the end, so didn't really need an investigation... I'll update the AC's.
