### ISSUE TITLE
Improve the test coverage for the code base

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#134]
We're lacking a lot of test coverage in the API and we need to work out the strategy for testing controllers and modules. We should have a time-boxed exercise to improve the test coverage for both the API and the UI.

**Acceptance criteria**:
- [x] The test coverage is higher than at the start of the story
- [x] An approach for testing the modules, services and controllers in the API has been outlined.
- [x] Quality gates have been set on the build at the current levels so that the coverage doesn't get worse - this level will be increased over time.

**Comment by ray-millward-tessella** [comment]
UI coverage is slightly down from before the start of the ticket due to additional work happening in other branches and using up the time-boxed scope on the API tests.
Here is the original coverage:
![image](https://user-images.githubusercontent.com/34268284/195573481-65f61223-5271-4531-9664-9da17e3f6307.png)
and here is the current coverage:
![image](https://user-images.githubusercontent.com/34268284/195573579-4497239f-2731-4673-a9a5-d8b687cf9581.png)

**Comment by ray-millward-tessella** [comment]
Here is the original API coverage:
![image](https://user-images.githubusercontent.com/34268284/195574014-03871c8f-2024-4372-9181-19f3a818e059.png)
and the current coverage which has been significantly improved:
![image](https://user-images.githubusercontent.com/34268284/195574130-b6a8579e-6d5e-42f0-8ff5-b7ebe0542300.png)

**Comment by colin-turner-cg** [comment]
All AC met:

1) See comments above
2) See `docs\architecture\ADRs\0008_unit_testing_api_components.md`
3) Gate coverage can be adjusted from the following files:
`src\API\package.json`
`src\UI\jest.config.js`
