### ISSUE TITLE
Document how to connect to the Azure database using an ssh tunnel

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#136]
Currently the database is only accessible from the deployment virtual machine (which is correct for security reasons). We should work out how to connect to the deployment machine using an ssh tunnel so we can both explore and back up the database from our development machines.

**Acceptance criteria**:
- [x] We can connect pgadmin to explore the Azure database for the system.
- [x] The process of running the ssh tunnel is documented in the SMG.

**Comment by colin-turner-cg** [comment]
All AC met.

I have been able to connect to the Azure database following the instructions in the SMG.

Part of the instructions in the SMG was not clear, however the SMG has been updated (see https://github.com/icipe-official/vectoratlas-software-code/pull/142).
