### ISSUE TITLE
Create a build for the API with PR triggers

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#16]
Create a build using GitHub actions for the api with corresponding pull request triggers so that a build happens when a pull request is made - merging should be blocked until the build passes.

**Acceptance Criteria**

- [x] A build exists for the api
- [x] The build runs when a pull request is created
- [x] Merging is blocked until the build passes.

**Comment by colin-turner-cg** [comment]
Acceptance criteria has been met as follows:

A build exists for the api - demonstrated by Andrew and evidenced by previous PRs.
The build runs when a pull request is created - demonstrated by Andrew and evidenced by previous PRs.
Merging is blocked until the build passes - demonstrated by Andrew, see PR [#61](https://github.com/icipe-official/vectoratlas-software-code/pull/61) for evidence that merging is blocked if an error in the build is detected.
