### ISSUE TITLE
Fix the display of lakes on the map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#160]
It looks like some lakes are missing or have been truncated. We should work out why these parts are missing and update the layers in the map to include them properly. We should also show the rivers and lakes at all zoom levels rather than below a certain point as the researchers use these to orientate the data based on where water sources are.

![image](https://user-images.githubusercontent.com/34268284/196152861-7c43cd71-b8e7-43fb-ba2d-06ae435f7f3d.png)

![image](https://user-images.githubusercontent.com/34268284/196152946-2d7f5f24-1fc1-41d7-aed3-3841ed0c03ec.png)

Acceptance criteria:
- [x] lakes don't have missing sections
- [x] large lakes are not missing from the map (particularly lake malawi)
- [x] lakes and rivers can be seen in all zoom levels.

**Comment by colin-turner-cg** [comment]
All AC met, test TC-4.1 added to STS
