### ISSUE TITLE
Register the vector atlas site with Google search

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#161]
Currently the site doesn't appear in any google searches - including a basic search for `site:vectoratlas.icipe.org` indicating it's not even known by Google. We need to get the vector atlas registered so it appears on search results.

This may involve adding a robots.txt file along with a site map but equally they may not be needed to register the site.

Acceptance Criteria:
- [x] The site can be found by a google search for `site:vectoratlas.icipe.org`.

**Comment by ray-millward-tessella** [comment]
I've now registered the site with Google Search Console - although this is linked to my gmail account so we might need to work out what the longer term plan is.
I've also added a robots file and a site map as well as uploading the site map to the search console.
Currently still waiting for google to index the site as no information is currently present - it says to come back in a day or so.

**Comment by ray-millward-tessella** [comment]
The site is registered in the search console https://search.google.com/search-console and this requires a file to be served from the site so it can be verified, this is currently at https://vectoratlas.icipe.org/googlef6d91c0904d8d267.html

I have also uploaded the site map and that is aware of the four different pages. We're just waiting for the crawler to run and results to appear.

![image](https://user-images.githubusercontent.com/34268284/196445447-b58652cf-940d-4e5d-88d4-1ab0935e3556.png)

**Comment by colin-turner-cg** [comment]
AC met, test TC-4.3 added to STS.
