### ISSUE TITLE
Update the marker style

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#162]
**Partially complete: See comments**

Update the marker style to use coloured circles with the count inside the marker, similar to the WHO threat map https://apps.who.int/malaria/maps/threats - the colours should be based on the species but should have an element of transparency so you can see overlaps and increasing density.

Acceptance Criteria:
- [x] The markers are round circles with the count in the middle.
- [x] The marker colour is based on the species for the occurence point.
- [x] Markers are partially transparent to allow for overlaps.

**Comment by Christopher-Sandbach** [comment]
The backend has been configured but requires tests to be written to reflect the updates. Aside from the changing of the icon to a circle, the frontend is untouched. Therefore, the queries will have to be updated and the marker colour hooked into species - the graphQL playground at http://localhost:3001/graphql should show that the data is available to query:

```
query Occurrence {
   OccurrenceData(skip:2, take:2){
    items{
    recorded_species{
      species{
        species
      }
    }
    }
  }
}
```

**Comment by colin-turner-cg** [comment]
All AC met, see test TC-4.4.
