### ISSUE TITLE
Get realistic data into the system

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#163]
Currently we don't have any realistic data for the system of sufficient size - we need to follow up with Marianne to get some realistic data and then ingest that in to the system so we can monitor the performance when the site queries and renders data.

The bigger the data the better and it can be wiped out and re-ingested later.

Acceptance criteria:
- [x] Get realistic data from Marianne, ideally we're looking for something of the order of 1000-2000 points.
- [x] The data is loaded in to the test instance.
- [x] Ensure data points load on the map view.
- [x] Any improvement stories resulting from testing are added to the backlog

**Comment by andykitch** [comment]
We have plenty of bionomics data (6000 rows) but not so much (valid) occurrence data (370 rows) - a lot of the occurrence data given was for non-Africa countries.

**Comment by andykitch** [comment]
We need to install some extensions to the server db to insert site data, but these are not enabled yet. I have emailed Kennedy to ask for these to be enabled.

**Comment by colin-turner-cg** [comment]
All AC met. Data points are visible on the map.
[Fix issue with large bionomics uploads #188](https://github.com/icipe-official/vectoratlas-software-code/issues/188) - bug raised for bionomics data upload
[Occurence data file contains NaN fields #200](https://github.com/icipe-official/vectoratlas-software-code/issues/200) - bug raised to fix test occurence data file
