### ISSUE TITLE
Wire up the ability to turn layers on and off

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#166]
Layers are now shown on the map view in the left hand view. We should wire up the ability to turn the layers on an off in the map when they are checked and unchecked in the left hand menu.

The overlays will be a case of rendering them or now, the layers in the base map will need the colour adjusting to make an individual layer invisible.

Acceptance criteria:
- [x] Overlays can be turned on and off on the map.
- [x] Base map layers can be turned on and off on the map.

**Comment by colin-turner-cg** [comment]
All AC met. See tests TC-4.6 and TC-4.7
