### ISSUE TITLE
Map reloads when loading map data markers and toggling layers

### ISSUE THREAD

**Issue by colin-turner-cg** [icipe-official/vectoratlas-software-code#170]
The map loads data in batches of 100. When a new batch of data is loaded it looks as though the map background is reloaded too, causing the screen to appear as if it's flickering.

**Comment by Christopher-Sandbach** [comment]
Old opacity slider commits for earlier demos may be of use as a similar issue was encountered and fixed at that time

**Comment by colin-turner-cg** [comment]
Tested and confirmed fixed. Tests added: TC-4.6, TC-4.7 and TC-4.8
