### ISSUE TITLE
Configure a basic model for the database and integrate with the API

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#18]
Configure a simple model (until we determine the proper model for the vector data) and script the creation of the relevant tables in the database.

Integrate this into the API using the TypeORM library and a corresponding object model for the tables in the database.

**Acceptance Criteria**
- [x] A simple data model exists in the database
- [x] The corresponding model objects exist in the code base
- [x] An example endpoint exists querying the database using these models and displays the output (possibly just in logs for now).

**Comment by colin-turner-cg** [comment]
Acceptance Criteria
 A simple data model exists in the database - demo'd by Andy and later confirmed by me.
 The corresponding model objects exist in the code base - saved at src\Database\DataModel_v1.xlsx
 An example endpoint exists querying the database using these models and displays the output (possibly just in logs for now)  - demo'd by Andy and later confirmed by me.
