### ISSUE TITLE
Investigate and document the process of migrations for the database.

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#19]
It is currently unclear what the best process for managing the database migrations is. We should investigate the standard options, are SQL scripts enough? TypeORM also offers a migration method in code but this may be more complicated than needed. Whatever method is chosen it needs to be scriptable to aid automation.

**Acceptance Criteria**
- [ ] Options for migrations have been investigated and documented on this story
- [ ] A decision on the approach has been recorded as an ADR.
- [ ] New stories for implementation have been added to the backlog.

**Comment by ray-millward-tessella** [comment]
I reviewed the outputs of the investigation as part of the PRs that went through.

**Comment by andykitch** [comment]
No stories were created from this - it will form part of our development process.

**Comment by colin-turner-cg** [comment]
Closing as complete.
