### ISSUE TITLE
Occurence data file contains NaN fields

### ISSUE THREAD

**Issue by colin-turner-cg** [icipe-official/vectoratlas-software-code#200]
When attempting to ingest data via the API (../vector-api/ingest/uploadOccurrence) an error is generated due to some of the data being detected as `NaN`. This is happening when trying to ingest using the file: `src\Database\test_data\occurrence.csv`

**Comment by ray-millward-tessella** [comment]
Check with Marianne if this is even possible with real data - can the Month/Year for a row be nullable?
