### ISSUE TITLE
Add ability to filter on more than one country and species

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#206]
Modify the existing country and species filters in the API to accept an array of strings rather than a single string, to allow filtering by multiple countries/species

AC's:
- [x] The existing country and species filters on the occurrence data endpoint in the API now accept arrays of strings instead of a single string, and will filter the results accordingly.

**Comment by colin-turner-cg** [comment]
The data I have in my local db has nine datapoints:

Filter for countries Mali and Guinea (1 data point on each) - I'm not worried about them not appearing geographically correct, that's just how my data has been set up:
![image](https://user-images.githubusercontent.com/109605071/204024691-28f8861a-b49c-4fc5-a0b1-411eb2ecdd37.png)

Filter for species Funestus  (1 data point) and Gambiae (5 data points):
![image](https://user-images.githubusercontent.com/109605071/204024933-594fea37-863d-4509-b3f0-941831746258.png)
