### ISSUE TITLE
Create an initial homepage with just the top navigation bar and routing

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#21]
Create an initial homepage with just the top navigation bar (that will be used across all pages) that displays the vector atlas name and logo. The site should also include routing with placeholder pages for the homepage and the interactive map page.

**Acceptance Criteria**
- [x] The site has a main navigation bar at the top that displays the name and logo of the vector atlas
- [x] There are placeholder pages for the homepage and the interactive map that can be navigated to from the navigation bar.

**Comment by colin-turner-cg** [comment]
All Acceptance Criteria met
 The site has a main navigation bar at the top that displays the name and logo of the vector atlas - confirmed.
 There are placeholder pages for the homepage and the interactive map that can be navigated to from the navigation bar - confirmed, the homepage exists at http://localhost:1234 and a link to the map page (http://localhost:1234/map) exists in the navigation bar.

**Comment by colin-turner-cg** [comment]
Also worth noting that the feature flag for Map needs to be set to true in src\API\public\feature_flags.json for the map link and page to be visible.
