### ISSUE TITLE
Display the main structure of the page on the homepage

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#22]
On the homepage display the main structure of the page. Add placeholders for the stats, news and download buttons. The Africa map should be a link through to the interactive map page. The initial UI mock up is shown below:

![image](https://user-images.githubusercontent.com/34268284/178978968-0427bea5-2d2f-44a8-bda2-822152464560.png)

**Acceptance criteria**
- [x]  Placeholders exist for stats, news and download buttons.
- [x] A short description of the Vector Atlas is shown on the page
- [x] A link exists for the interactive map. The background image shouldn't be too big if being loaded on a poor connection (1Mb/s)

**Comment by ray-millward-tessella** [comment]
Aim for under 20 seconds for a 1Mbit/s connection, ideally under 10s.

**Comment by colin-turner-cg** [comment]
All acceptance criteria met, I've visually confirmed that placeholders exist for stats, news, download buttons and an Africa map exist on the homepage. The Africa map links to the map page. Testing using Chrome with a 1Mb/s throttle applied has found the average home page load time is 3s to 4s and average map page load time is 7s to 8s.

A short description of the Vector Atlas is shown on the page -  the text for this was changed in https://github.com/icipe-official/vectoratlas-software-code/issues/55.
