### ISSUE TITLE
Map not displaying correctly

### ISSUE THREAD

**Issue by colin-turner-cg** [icipe-official/vectoratlas-software-code#220]
After certain actions are performed on the website the map appears shifted to the left (see screenshot below):

![image](https://user-images.githubusercontent.com/109605071/201133443-a0e9616b-fccb-4055-893d-5825d57f8caa.png)

Steps to replicate:

1) Expand the overlay/base map drawer
2) Go to About or Home page
3) Go back to Map page (the drawer should appear expanded)
4) Collapse the overlay/base map drawer

This occurs on the current builds on both localhost and https (as at 15:00 10/11/2022).

**Comment by colin-turner-cg** [comment]
@Christopher-Sandbach as discussed, the map page is still intermittently showing the behavior reported. However now, it seems that only loading a non-cached version of the site (i.e. with cache disabled in Dev tools) causes the white space to the right of the map to be seen when closing the drawer.

**Comment by Christopher-Sandbach** [comment]
I have tried to recreate the error, as discussed in our call, on my machine but I am unable to do so - resizes the map correctly. Tis weird. Might be worth seeing if others can do so. We can raise it during stand-up tomorrow

**Comment by colin-turner-cg** [comment]
This issue still persists but is more harder to replicate now. It occurs very intermittently and seems to only occur if the drawer is collapsed at a point where the map is loading in data.
