### ISSUE TITLE
Make all map marker API filters accept arrays

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#224]
Currently the country and species filters on the Occurrence endpoint accept arrays. We need all other filters to accept arrays, except the timestamps.

AC's:
- [x] All filters, except timestamps, on the occurrence data endpoint in the API now accept arrays of strings instead of a single string, and will filter the results accordingly.

**Comment by colin-turner-cg** [comment]
Currently larval/adult data and control do not accept arrays. Work to implement this functionality for those fields and date ranges is currently being done by Andrew on [107](https://github.com/icipe-official/vectoratlas-software-code/issues/107).

**Comment by colin-turner-cg** [comment]
An array can be entered and sent as a query for country, species and season, results are returned (based on current data).
![image](https://user-images.githubusercontent.com/109605071/208649327-8b083415-c881-45c4-bf53-823b6b4c0036.png)
