### ISSUE TITLE
Add navigation to source pages

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#225]
The two source pages (`/sources` and `/new_source`) need to be navigable to. They are not used enough to have links on the homepage, so an alternate solution needs to be implemented - maybe having a `More` dropdown in the navbar

AC's:
- [x] Links exist for the two source pages (`/sources` and `/new_source`) in a clear location

**Comment by colin-turner-cg** [comment]
- The two source pages (/sources and /new_source) appear under the `More` link in the navbar

**Comment by colin-turner-cg** [comment]
Tests 5.1 to 5.3 written
