### ISSUE TITLE
Add a download button for each overlay

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#230]
Modellers need to be able to download the source data for each overlay to use in their own models. For the initial version we should add a download button for each overlay (not the base map) that downloads the original file used to create the overlay (likely a geotiff). This should be a static file download from the server for now but in future we should stream this from Azure blob storage so we don't need a lot of disk space on the server.

**Acceptance criteria**
- [x] Users can download the full geotiff for each layer in the layers section of the map view.

**Comment by colin-turner-cg** [comment]
Tested with two different overlay files I uploaded:

![image](https://user-images.githubusercontent.com/109605071/211809299-06fbb303-0b54-4abe-805f-820a121fd633.png)
