### ISSUE TITLE
Set up automated UI tests in Cypress

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#24]
Given the high developer to tester ratio for the project we need to invest in automated regression tests using Cypress. We should set up a new suite of automated acceptance level tests for the site given a full system to point to.

Initial tests might just check that the user can navigate to the home page and that it contains expected components as well as the ability to navigate to the interactive map. Normally these tests would be much longer than unit tests, they are designed to reflect user workflows.

We do not need to run them as part of a build yet as we don't have a deployed system to check against - this would be a target for future.

**Acceptance Criteria**
- [x] A regression suite can be run using Cypress.

**Comment by colin-turner-cg** [comment]
Initial set of Cypress tests can be found in `e2e\cypress\e2e`. More tests will be added over time as development progresses.
