### ISSUE TITLE
Add toast notification on all and filtered downloads

### ISSUE THREAD

**Issue by Christopher-Sandbach** [icipe-official/vectoratlas-software-code#250]
Functionality for downloading has been implemented but pop-up notifications can now be included

**Comment by colin-turner-cg** [comment]
A pop  up similar to the one in the image appears on all downloads.
![image](https://user-images.githubusercontent.com/109605071/204855980-5731b2b8-591d-4868-bb3c-c8446ac3d6b3.png)
