### ISSUE TITLE
TechDebt: Pull out actions to separate folder

### ISSUE THREAD

**Issue by Christopher-Sandbach** [icipe-official/vectoratlas-software-code#251]
In my notebook from last week...

Currently, our actions are nearly entirely within the slices themselves. Ideally, these should be pulled out into a number of separate actions folders/files, each folder corresponding to a separate slice.

**Comment by colin-turner-cg** [comment]
I've spoken with Chris about this story. I've taken a look inside the `UI/state` folder and can see that the sections there have slice files and an actions folder.
