### ISSUE TITLE
Cleaning up disk space on the deployment environment

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#262]
We had an issue during deployment where we couldn't deploy a new version because the virtual machine ran out of disk space. This was because all the previous docker layers were still on the machine. Running `docker system prune -a` removed the old layers and freed up space but someone now needs to do that on a regular basis.

We should assess whether we can run the clean up during each deployment or if there are alternative options. Maybe a cron job, but we need to question if we can do this without impacting the running system. An idea is mentioned here https://nickjanetakis.com/blog/docker-tip-32-automatically-clean-up-after-docker-daily

**Acceptance criteria**:
- [ ] Document the findings of the investigation on this ticket.
- [ ] Write a new story to cover implementing the clean up on a regular basis.

**Comment by shishi5089** [comment]
@colin-turner-cg Hello Colin, the findings of the investigation are in the ` /docs/SMG/07-maintenance.md`. The script was also added to the server in the `/etc/cron.weekly` folder for system prune every week. Hope this is what you are looking for
