### ISSUE TITLE
Add a new species information API route and database table

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#263]
In order to build a new species information page we need to have that information in the database and served via the graphql api. Create a new database entity for species information with columns for species name, description and image (which will be a base64 string).

Add a corresponding paged resolver for querying this list.

**Acceptance criteria**
- [x] users can query for a list of species information that includes the name, description and an image of that species as a base64 string.
- [x] the route is open to all users (the creation route later will only be for editors).

**Comment by colin-turner-cg** [comment]
![image](https://user-images.githubusercontent.com/109605071/208460254-b2f27790-8430-4d57-bfcd-bb3777576538.png)
