### ISSUE TITLE
Add a new route to create a species information entry

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#265]
Add a new route to the graphql api to allow an editor to create a new species information entry - this should include a name, description and the image in base64. Only users with the editor role should be able to use this route.

**Acceptance criteria**
- [x] The is a new graphql route for creating a new species information entry.
- [x] The new route validates that there is a name, description and image as a string (no validation it is actually an image is needed and it can be empty).
- [x] The route can only be used by a user with the editor role.

**Comment by colin-turner-cg** [comment]
With editor role:
![image](https://user-images.githubusercontent.com/109605071/208468854-61775788-06d7-41e0-9c11-59f5e3827cad.png)

Without editor role:
![image](https://user-images.githubusercontent.com/109605071/208470148-4deb5784-cd07-48e2-b78d-bc0d20a58506.png)
