### ISSUE TITLE
TechDebt: Fix console errors in tests

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#273]
The tests currently return console errors when run. These need to be fixed.

AC's:

- [ ] When `npm run test` is run in the UI project, no console errors can be seen.

**Comment by colin-turner-cg** [comment]
I asked Andrew to run the `npm run test` command for me, here is the output:

![image](https://user-images.githubusercontent.com/109605071/207043057-e0b4ed38-0f8d-44fe-9067-2e7c77aba8c3.png)

TC-6.1 in STS
