### ISSUE TITLE
Record when a visitor first loads the site to track visitor counts

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#29]
In order to show the effectiveness of the site we need to record when visitors come to the site, this can be done by registering a callback when the site first loads. We should include country information if the user approves geo-location in the browser (only country information and nothing more specific) otherwise just record it as an anonymous visit.

These state will eventually allow us to create a report of where visitors are coming from to the Gates Foundation but also to show the number of visits in the statistics section of the homepage.

**Acceptance Criteria**:

- [ ] A visit is recorded on the server when the site is loaded.
- [ ] If the user consents to using their location then a country is recorded with their visit.
- [ ] If the user doesn't consent to use their location then just an anonymous visit is recorded.

**Comment by andykitch** [comment]
Superseded by #286
