### ISSUE TITLE
Add file upload mechanism for model uploads

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#298]
The UI needs a new component to upload model files. This will initially live on it's own page, but is destined for the user dashboard when it's been created.
This page allows a user with the uploader role to upload a model output, either zip or tif. This calls an API endpoint which accepts file uploads and stores them in a sensible place on the server for now, with a view to storing them on Azure blob storage eventually.
Both the page in the UI and the API endpoint are restricted to users with the uploader role.

AC's:

- [x] The UI includes a page (/model_upload) which contains a file upload control and 'Upload' button
- [x] The user can upload only a .zip or .tif file to the page, and click the 'Upload' button
- [x] This click sends the selected file to a new API endpoint, which is also callable through e.g. postman. This endpoint is at `/models/upload`
The API then stores the uploaded file locally in a suitable place (documented on this story) -  this has been superseded by the blob storage location #311 
- [x] Both the page in the UI and the API endpoint are restricted to users with the uploader role.

**Comment by andykitch** [comment]
Model files are stored in /data/vector-atlas/models. This folder will have to be created manually first for the upload to work.

**Comment by andykitch** [comment]
The files are now saved on the blob store, as in #311

**Comment by colin-turner-cg** [comment]
An upload page exists at `/model_upload` and is only accessible to users with the `uploader` role

![image](https://user-images.githubusercontent.com/109605071/211604033-c3fef146-1015-4152-9b6e-d4211342ee84.png)

Model files can be uploaded via an api call using a bearer token with the `uploader` role

![image](https://user-images.githubusercontent.com/109605071/211602309-f17f8e7e-e4e9-4e7a-9f08-aff1aea83b91.png)

Using a bearer token without the `uploader` role returns "401 - unauthorized"

![image](https://user-images.githubusercontent.com/109605071/211603102-40870e6c-8be6-4f57-93d6-134f846252c4.png)

Removing the bearer token also returns "401 - unauthorized"

![image](https://user-images.githubusercontent.com/109605071/211603597-96ab9376-2f1a-4a8b-96aa-158344e0adf0.png)

**Comment by colin-turner-cg** [comment]
I was able to upload a csv file via the UI

![image](https://user-images.githubusercontent.com/109605071/211605616-e50971eb-ff79-4ca4-ace0-a1cc59ee6228.png)

![image](https://user-images.githubusercontent.com/109605071/211605739-5cc241b5-525f-445a-ad21-d350187b8253.png)

Moving story back to `In Progress`, A/C states only .shp or .tif files should be up loadable.

**Comment by colin-turner-cg** [comment]
We've also found a bug relating to the file upload size limit. This is currently set to 2mb which means that the file upload will need to be handled in chunks with a limit of 2mb. I've already spoken to Andrew about this.

**Comment by colin-turner-cg** [comment]
The bug relating to non allowed file types and upload size has been fixed.
