### ISSUE TITLE
Generate tile server layer from file

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#299]
New API endpoint for triggering transformation of model output to tile layer file.
Should return status of job.
Calling again checks if the process is still running.

**Acceptance Criteria**:
- [x] Calling the new API endpoint downloads the model output from blob storage, transforms it and puts the new mbtiles file in the overlays folder for the tile server.
- [x] The API endpoint returns a running status whilst the process is running.
- [x]  The API endpoint returns an error status if the process fails (e.g. the blob doesn't exist)
- [x] The API endpoint returns a done status when the transformation is complete.
- [x] The transformation process updates the map config files for the API with the new layer.
- [x] Refreshing the UI after the transformation has completed and the config reloaded then adds a new layer to the map overlays.

**Comment by ray-millward-tessella** [comment]
The new endpoint is on the graphql api http://localhost:3001/graphql with body:
```
query {
  postProcessModel(
    modelName: "an_gambiae_map7", 
    displayName: "Anopheles Gambia 7",
    maxValue: 1.0,
    blobLocation: "models/an_gambiae_map/1671455121181_an_gambiae_map.tif"
  ) {
    status
  }
}
```
and returns a response like:
```
{
  "data": {
    "postProcessModel": {
      "status": "DONE"
    }
  }
}
```

**Comment by ray-millward-tessella** [comment]
In the test-local environment you can connect the Azure storage explorer to the blob storage emulator in the stack (it does this automatically because it knows about the emulator). You can then upload blobs here. Alternatively connect to the test environment blob storage directly and use the test environment.

**Comment by colin-turner-cg** [comment]
AC1 and 2 - new files in `overlays` folder and `running` status returned:

![image](https://user-images.githubusercontent.com/109605071/211811717-01e1f443-09ae-4c21-979a-000b3dd6e001.png)

AC3 - error when pointing to a non-existent blob:

![image](https://user-images.githubusercontent.com/109605071/211812079-12c5026f-6395-4824-b147-63da854d24ca.png)

AC4 - `Done` status returned:

![image](https://user-images.githubusercontent.com/109605071/211811875-8ef8d020-708c-40ff-9f7a-38b7e59736b9.png)

AC5 - `map_overlays.json` updated:

![image](https://user-images.githubusercontent.com/109605071/211812857-7c31c4e1-801b-4f96-9789-2467989e1793.png)

AC6 - new overlay layers visible after UI refresh

![image](https://user-images.githubusercontent.com/109605071/211813306-07426921-7659-40a9-a4b9-d0838f32fafe.png)
