### ISSUE TITLE
Create a basic api with Nest.js and GraphQL

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#3]
Create an initial API for the main website using the Nest.js framework along with the graphql quick start https://docs.nestjs.com/graphql/quick-start

**Acceptance criteria**

- [x] A new api runs and is accessible from the website in a local development environment.
- [x] An example graphql endpoint exists on the api (this might return a fixed version number)

**Comment by colin-turner-cg** [comment]
Acceptance criteria
A new api runs and is accessible from the website in a local development environment
An example graphql endpoint exists on the api (this might return a fixed version number)

Both confirmed by running a POST request to http://localhost:1234/vector-api/graphql and having relevant data returned.
