### ISSUE TITLE
Record the number of downloads against each row of data and the total downloads

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#30]
We need to record when someone downloads data to show as a statistic on the homepage. As well as the overall count of downloads we should also record how many times an individual row of data has been downloaded - this will be useful for uploaded to see the value of the data they are providing.

**Acceptance Criteria**
- [ ] Clicking on the download data buttons increments the count of downloads in system.
- [ ] When data is downloaded then the counts for each of the data items are increased by 1. The download count is shown in the `download_count` column of the occurrence table.
- [ ] Clicking the download data button on the map fires an analytics event, which shows up on the analytics dashboard

**Comment by andykitch** [comment]
Just on occurrence data for now

**Comment by Christopher-Sandbach** [comment]
Add new column to occ and bio entity with a download count. When it is downloaded, +1 to the download count

**Comment by colin-turner-cg** [comment]
I've verified that the download count increases by one when the download data button is clicked

Event recorded in Umami:
![image](https://user-images.githubusercontent.com/109605071/216088218-2b65cf27-d079-4560-8574-74f6b2b35eef.png)
