### ISSUE TITLE
Update tile server config and reload somehow

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#300]
We need to work out how to update the tile server config file to serve a new layer and reload whilst the site is running.
Need to investigate if tileserver-gl can watch the config file or has a reload mechanism - ultimately could work how to restart the tile container.

Ultimately we can watch the tile layer folder with a cron job and restart the container if a new file appears. This will need a mechanism to know when a file was added.

**Acceptance criteria**:
- [x] The tile server can be restarted when the config changes.

**Comment by ray-millward-tessella** [comment]
I've updated the tile server image to include a script that watches for a trigger file. When the API updates the trigger file then it causes the tile server to reload by sending the appropriate signal.

**Comment by colin-turner-cg** [comment]
Terminal output after adding a new overlay file to my local Blob storage and sending an API query to trigger a model process:

![image](https://user-images.githubusercontent.com/109605071/211810374-4000fe8c-0078-459f-ba71-92639f09e02a.png)
