### ISSUE TITLE
Add content to the help site

### ISSUE THREAD

**Issue by Christopher-Sandbach** [icipe-official/vectoratlas-software-code#312]
We currently have a help site but it does not contain any information. We will need to liaise with Marianne how to prioritize this story - when does she want it added? Does she want it constantly updated or simply added prior to handover?

You should outline a number of areas of the site, their intended purpose and how to use them in detail. For example:

- Upload: How does our upload procedure work? What files does it accept and what format/template do you need? How do you upload? What permissions do you need? A link to a general page on how to obtain those permissions. How are the uploads reviewed and by whom? Where can you track it? How can you contact if an upload has been reviewed in x amount of time with a guide on how long to wait? Troubleshooting uploads - the types of errors, examples, how to fix? Who to contact if broken?

- Downloads: Where to go to download data. How to download all or filtered data. What is the structure and file type of the downloaded data. If broken who do you contact

- Map: How to use the  functionality on the map. Maybe an example...

etc.

We want to have good general coverage of the core functionality on the first pass of this. Following that, general amendments and changes can be made when necessary 

AC's:

- [x] Content covering basic functionality of website added. Upload. Download. Map use. User settings/roles

**Comment by colin-turner-cg** [comment]
See:
https://vectoratlas.icipe.org/help/Contributing%20data%20to%20the%20atlas/Uploading%20data
https://vectoratlas.icipe.org/help/Exploring%20the%20data/Downloading%20data
https://vectoratlas.icipe.org/help/Exploring%20the%20data/Using%20the%20map
https://vectoratlas.icipe.org/help/Contributing%20data%20to%20the%20atlas/Signing%20up%20to%20the%20site
