### ISSUE TITLE
Add an about us page

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#32]
Add an about us page with a description about the Vector Atlas project, contacts and the team. Show the list of partners and their logos.

**Acceptance Criteria**

- [x] Users can navigate to an about page
- [x] The about page shows a description of the project, contacts and the team.
- [x] There is a list of partners and their logos.

**Comment by colin-turner-cg** [comment]
All acceptance criteria has been met:

I am able to navigate to an about page, which contains a description of the project, has contact and the team information on it, and contains a list of partners and their logos.

Test cases 1.1 to 1.5.
