### ISSUE TITLE
Change dataset table to include reviewer array

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#346]
The dataset entity needs changing to allow for multiple reviews. The lastReviewBy and lastReviewedAt columns should be arrays of strings and timestamps accordingly, and approvedBy and approvedAt columns need adding.

AC's:

- [x] The dataset table in the db now has the ReviewedBy, ReviewedAt, ApprovedBy and ApprovedAt columns as arrays, after the latest migration has been applied.

**Comment by colin-turner-cg** [comment]
The new columns can be seen in the `dataset` table.
![image](https://user-images.githubusercontent.com/109605071/217484600-04902582-9499-4b7e-9f32-edd7d116f7f5.png)
