### ISSUE TITLE
Add a Data page

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#349]
We need a 'Data' landing page for users to access the model upload, data upload etc. pages. This should be reachable from a link in the navbar.

- [x] There is a new 'Data' page, accessible at vectoratlas.icipe.org/hub
- [x] This new page has a link in the navbar
- [x] The page contains links to the model upload and data upload pages for now

**Comment by colin-turner-cg** [comment]
Test created: TC-7.7
