### ISSUE TITLE
Investigate how we might allow users to login with GitHub or Gmail

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#35]
The upload pages and the news editing pages need to be secured, it would be good to make it easy for users to log in by using their GitHub or Gmail accounts. This investigation is to determine if we can do that using something like https://www.passportjs.org/ and what the authorisation process might be - they might be able to log in but then there needs to be some process of making them an uploader or news editor. Does this mean we need admin pages for setting roles or would this be done directly in the database?

**Acceptance criteria**

- [ ] The output of the investigation is documented in the ADR
- [ ] New stories resulting from the investigation have been created.

**Comment by andykitch** [comment]
New stories = #56 & #57

**Comment by ray-millward-tessella** [comment]
I reviewed as part of the ADR PR, Auth0 looks like the clear route to go.

**Comment by colin-turner-cg** [comment]
Closing as complete.
