### ISSUE TITLE
Add a login page for upload and news editing

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#37]
Add a login page that is only triggered if someone tries to navigate to the upload pages or the news editing pages. Typically this means wrapping the routing in an authorisation wrapper.

**Acceptance Criteria**
- [ ] If the user is not logged in and tries to go to the upload pages then they are redirected to the login page, upon successful login then they are directed back to the upload page.
- [ ] If the user is logged in and goes to the upload page then it will let them through.
- [ ] If the user isn't logged in and goes to the news editing page then they are redirected to the login page, upon successful login they are directed back to the news editing page.
- [ ] If the user is logged in and goes to the news editing page then it will let them through.

**Comment by andykitch** [comment]
Superseded by other stories
