### ISSUE TITLE
Investigate using https with the site

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#38]
The site needs to be deployed at a https address, this will likely need certificates of some sort and we should investigate options for getting certificates. Do we need to purchase a certificate or can we generate a free one using cert-manager?

**Acceptance Criteria**
- [x] Outputs of the investigation are documented in the ADR
- [x] New stories resulting from the investigation have been created.

**Comment by andykitch** [comment]
Created #58 for this

**Comment by ray-millward-tessella** [comment]
I've reviewed the output of this as part of a PR for the ADR, looks straightforward with CertBot.

**Comment by colin-turner-cg** [comment]
Closing as complete.
