### ISSUE TITLE
Admin page to change roles

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#382]
We need a page for admins to be able to change a user's role. This page should only be accessible to the admin role. It should contain a table of users of the system, including their auth0 id, their email address (got from [the auth0 API](https://auth0.com/docs/manage-users/user-search/retrieve-users-with-get-users-endpoint)) and the roles they currently have, as checkboxes. The admin user should be able to check any checkbox to give or remove permissions, and click a save button, which should make an API call (also restricted to admin users) to change the user_role table in the db. This page should be accessible under the `More` NavBar option, but the link should only be viewable to admin users.

AC's:
- [x] A page exists at /admin, restricted to admin users only
- [x] A link to the page exists under the `More` navbar option, only viewable to admin users
- [x] The page contains a table with all users of the system. The list should come from auth0, not the user_role table
- [x] The table should contain the user's auth0 id, email address, and checkboxes for the roles. Any existing roles are already checked
- [x] The user is able to click the checkboxes to change the roles, and click a 'Save' button
- [x] Clicking 'Save' calls a new API endpoint, which is only accessible to an admin user. This endpoint changes the state of the user_role db table, changing roles of existing users in the request and adding rows for new users in the request

**Comment by colin-turner-cg** [comment]
Tests 7.11 to 7.14 added to test script - all pass
