### ISSUE TITLE
Add code quality targets for linting, unit tests and code coverage 

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#4]
Add targets in the package.json for running linting, linting with fixes, unit tests (both complete runs and watching changes) and the complete run should collect coverage (this will some configuration of which files to ignore).

**Acceptance Criteria**

- [x] The web app has targets for linting and linting with automatic fixes.
- [x] The web app has a target for running tests and outputs coverage.
- [x] The web app has a target for running tests whilst watching for changes.
- [x] The api has targets for linting and linting with automatic fixes.
- [x] The api has a target for running tests and outputs coverage.
- [x] The api has a target for running tests whilst watching for changes.

**Comment by colin-turner-cg** [comment]
Andrew has demonstrated to me on a Teams call/screen share that the all of the acceptance criteria has been met.
