### ISSUE TITLE
Add a download button for the current selection of data

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#40]
When a user has filtered a selection of data on the interactive map view then they should be able to download that selection. A button should be added to the interactive map page to allow you to download the current selection of data.

**Acceptance Criteria**

- [ ] There should be a button on the interactive map to allow you to download the current selection of data.
- [ ] The downloaded csv file should only contain data within the given area as well as the given filters.

**Comment by andykitch** [comment]
Duplicate of #108
