### ISSUE TITLE
Add help content for upload & review process

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#437]
Help content needs to be added for the data upload and review process, with screenshots.

AC's:
- [x] Help content exists for the data upload and review process, with screenshots.

**Comment by colin-turner-cg** [comment]
See:
https://vectoratlas.icipe.org/help/Contributing%20data%20to%20the%20atlas/Uploading%20data
https://vectoratlas.icipe.org/help/Contributing%20data%20to%20the%20atlas/Reviewing%20data
