### ISSUE TITLE
Investigate different map providers for displaying an interactive map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#5]
We will need an interactive map of some sort for the site, we should investigate different options that allow us to integrate with React. We also need to identify options for the underlying base layer and what the license models with it are - do we need to run our own tile server to provide the map data?

**Acceptance Criteria**
- [ ] Outputs of the investigation are documented here
- [ ] New stories from the outputs have been added to the backlog.

**Comment by andykitch** [comment]
Putting this on hold until we meet with MAP team

**Comment by andykitch** [comment]
Met with Camilo from the MAP team - he recommended OpenLayers

**Comment by ray-millward-tessella** [comment]
I've reviewed the outputs and it overlapped with story #7

**Comment by colin-turner-cg** [comment]
New stories created, overlap with story [#7](https://github.com/icipe-official/vectoratlas-software-code/issues/7). Closing as complete.
