### ISSUE TITLE
Create an initial data model

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#51]
Using the Vector Atlas datasets shared, create an initial data model for the database. This will detail the tables, columns, data types and inter-table links that will form the data model. 

Acceptance Criteria:

- [x] Initial data model exists in the codebase, in a format that is easily read by non-technical people (Excel)
- [x] The data model has been reviewed and approved by appropriate members of the wider Vector Atlas team

**Comment by andykitch** [comment]
Initial data model created, and sent to team for comment

**Comment by colin-turner-cg** [comment]
Acceptance Criteria met
1) Initial data model exists in the codebase, in a format that is easily read by non-technical people (Excel) - DataModel_v1.xlsx is saved in src\Database.

**Comment by andykitch** [comment]
We had a meeting with Marianne on 30/08 about the data model - we discussed the links between entities, and how the data will be imported. The data model will be an evolving thing - this is not the final version, it will change as we develop the data ingest process.
