### ISSUE TITLE
Develop a script to build the base map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#52]
Using the output from the tile server investigation #7 , develop a script to download data from natural earth https://www.naturalearthdata.com/downloads/ and convert to a combined mbtiles file using ogr2ogr and tippecanoe (a second script to install the needed software should also be built).

The layers needed are:
- cultural/admin 0 countries
- physical/land
- physical/oceans
- physical/rivers + lake centerlines
- physical/lakes + reservoirs

It may be possible to only show the rivers and lakes at zoom levels below level 3 and we should see if this is possible. If not then having at all zoom levels is ok.

Acceptance Criteria:
- [x] A script exists to install the software needed for the main base map script (e.g. installs gdal-bin and tippecanoe)
- [x] A script exists that downloads all of the layers above from Natural Earth and converts them to a combined mbtiles file.
- [x] The binary files are ignored from the codebase (they can be large and shouldn't be checked in).
- [x] The resulting mbtiles file should be mountable in a tileserver-gl instance and each of the layers above should be visible and in the legend.
- [x] Either rivers and lakes should only be visible below zoom level 3 or we should have determined this isn't possible.

**Comment by colin-turner-cg** [comment]
All acceptance criteria met:

Scripts exist that install the base map and download required layers.
Binary files have been excluded from codebase.
Legend can be seen on tileserver.
Rivers and lakes are visible once zoomed in by two or more levels from default (assuming default = 5).
