### ISSUE TITLE
Add a tile server to the system

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#53]
We need to add a tile server using tileserver-gl to the system to serve maps and model output layers. The details are in the tile server investigation #7 . The main dockerfile needs to be updated to run the tile server as well as the development dockerfile.

Part of the complexity will be around the fact that Rancher Desktop doesn't mount files correctly when used with docker-compose https://github.com/rancher-sandbox/rancher-desktop/issues/2461 so we may have to run the base map building script as part of the dockerfile or assume it has been run externally so we can copy the mbtiles files into the image.

Acceptance criteria:
- [x] A tile server can be started as part of the local development set up that serves the maps generated from #52 
- [x] A tile server is integrated into the docker compose stack for the production environment that serves the maps from #52 
- [x] Determine if it is possible to mount files using Rancher Desktop as this is our current testing environment - this is less important when deployed to the final server.

**Comment by colin-turner-cg** [comment]
All acceptance criteria met:
A tileserver can be started with `docker compose up`, it has been found that Rancher Desktop can mount files.
