### ISSUE TITLE
Add a new interactive map using OpenLayers

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#54]
Add a component that displays the base map for the vector atlas using OpenLayers and data from the tile server deployed in #53 . The investigation was done in #7 and more details in #5. An example is in the `investigation/map-rendering` branch https://github.com/icipe-official/vectoratlas-software-code/tree/investigation/map-rendering.

Acceptance criteria:

- [x] The map page should show the base map where data comes from the tile server.
- [x] Styling should be applied and configurable outside of the component (e.g. as part of the theme) - it doesn't need to be outside the code yet but that may be a future step.

**Comment by colin-turner-cg** [comment]
All acceptance criteria met:

Map page is visible following Map link from nav bar or at http://localhost:1234/map.
Styling can be applied and configured outside of the component using src\API\public\map_styles.json and src\API\public\map_overlays.json.
