### ISSUE TITLE
Change text on homepage

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#55]
The text in the 'About' box on the homepage needs to be changed to the following:

Analyses-ready data and spatial models specifically tailored to inform malaria vector control
|
The Vector Atlas brings together a new collaboration of partners (icipe, University of Oxford, MAP, PAMCA, GBIF, VectorBase, IRMapper, BMGF) in an initiative to build an online, open access repository to hold and share our analyses-ready malaria vector occurrence, bionomics, abundance, and insecticide resistance data.  Our data will be fully up to date and form the basis of a series of spatial models specifically tailored to inform the control of mosquito vectors of disease.

**Comment by colin-turner-cg** [comment]
I can confirm that the text is visible on the homepage.
