### ISSUE TITLE
Add auth0 login to the UI

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#56]
Certain pages of the UI (data upload, data review, news editing) should only be accessible to authenticated and authorised users. We will use Auth0 to handle the auth workflow, as documented in the 0005_login ADR. 

This story covers adding the @auth0/nextjs-auth0 library to the UI, and adding a login feature, probably following https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/#Next-js-Serverless-Deployment-Model. The application will need to be registered with Auth0 first.

Acceptance Criteria:

- [x] The Vector Atlas app is registered with Auth0
- [x] A user has the ability to log in to the UI, using the Auth0 login
- [x] Once logged in, the UI shows the username in an appropriate place on the navbar

**Comment by colin-turner-cg** [comment]
A Auth0 login has been created and used to login in successfully. The username used to login is displayed after clicking on an icon on the navbar in the top right corner of the website.
