### ISSUE TITLE
Set up certificates on the server

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#58]
When the server has been provisioned, use Let's Encrypt and certbot to set up certificates so we can use https. See https://certbot.eff.org/instructions?ws=nginx&os=ubuntubionic

Either run against the deployed version by integrating with the nginx reverse proxy or deploy a simple nginx server and show integration works.

Acceptance Criteria:
- [x] The vector atlas site is available over https

**Comment by ray-millward-tessella** [comment]
We may need to get a certificate from ICIPE if we are on the icipe.org domain. There is a risk this story is more complicated.

**Comment by colin-turner-cg** [comment]
Site is fully accessible via the URL https://vectoratlas.icipe.org/, all internal links work and link to secure pages.
