### ISSUE TITLE
Create intial tables from data model

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#59]
The initial Bionomics and Occurrence tables need to be created from the data model stored in `src/Database/DataModel_v1.xlsx`. These will need to be created as entity files in the API folder, following the example set by the geo_data.entity file, and replacing said file and associated files. Connections between the tables should be created, and the changes should be applied to a local database before a new dump script is generated to replace `db_dump.sql`. 

Acceptance Criteria:
- [x] All the sheets currently in `DataModel_v1.xlsx` are represented as entity files in the API project, with appropriate data types as defined in the data model sheets
- [x] Appropriate other files (model, module, resolver, service) exist for the new entities, which allow data extraction at the Bionomics and Occurrence level (but not lower down)
- [x] The `db_dump.sql` file in the Database folder has been updated to reflect the new state of the data model. When the db docker container is started, this sql file is used to create the correct tables in the dockerised db, and the API can connect to this db without error.

**Comment by colin-turner-cg** [comment]
`db_dump.sql` is now called `init_db.sql`

**Comment by colin-turner-cg** [comment]
All AC met. I had to clear and rebuild my local environment to see the new changes to model/database.
