### ISSUE TITLE
Investigate displaying our own GeoJSON as a base layer for the map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#6]
An alternative to displaying a full blown detailed map as the base layer is to display a GeoJSON outline of the countries of Africa. We should investigate if this is possible and how big the map would be. What is the performance like downloading on a 1MB/s connection? There may be options to hold the file in the public folder and transfer as a gzip file (this can be automatically done by the server and browser).

**Acceptance Criteria**
- [ ] Outputs of the investigation are documented here
- [ ] New stories from the outputs have been added to the backlog.

**Comment by andykitch** [comment]
GeoJSON file for Africa country borders generated from https://geojson-maps.ash.ms/ is 2MB, and works fine when hosted in UI code. I'll investigate moving it to the API code, and see what the loading speeds are like with a slower connection.

**Comment by andykitch** [comment]
Hosting the geoJSON in the `/public` folder in the UI allows next to auto-compress the 2MB file to 850kB, which loads pretty quickly, even with a 1Mbit/s connection.

**Comment by andykitch** [comment]
This is not the way we will do things - the geoJSON file is too large

**Comment by ray-millward-tessella** [comment]
I've reviewed the investigation and the system has moved on from this point.

**Comment by colin-turner-cg** [comment]
Ray and Andy have commented that a decision has been made and geoJSON will not be used.
