### ISSUE TITLE
Load initial data in to new tables from spreadsheets

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#60]
A new process to load data into the tables created in #59 needs to be created. Spreadsheets exist in the Google Drive for Bionomics and Occurrence data. This needs to be ingested into the database through a re-usable process, either via an endpoint in the API (if easily done) or through a bash script.

- [x] A process exists to ingest csv Bionomics and Occurrence data into the database. 
- [x] The process is documented in the SMG
- [x] The docker db container is initialised with this new data

**Comment by colin-turner-cg** [comment]
SMG needs to be updated with the process

**Comment by andykitch** [comment]
The third AC will be covered by #97

**Comment by colin-turner-cg** [comment]
All AC met:
Bionomics and Occurrence exist in the database.
Data load process is documented in the SMG under 10-working-with-the-database
The docker db container is initialised with this new data - see note from Andy above.
