### ISSUE TITLE
Split species table

### ISSUE THREAD

**Issue by andykitch** [icipe-official/vectoratlas-software-code#62]
The existing Species table needs to be split, into one table containing a pre-designated list of species names, and one containing the rest of the species info. 

Acceptance Criteria:
- [x] The database now contains two species-related tables - `species` for holding constant species info, and `recorded_species` holding species info related to a certain record. There should be a many-to-one relationship between the two
- [x] The `species` table should be initialised with the list of species as in the attachment. These should all have a reference to the data source.
- [x] The data ingest process has been modified to link new records to the existing species table.

**Comment by andykitch** [comment]
Requested the list from Marianne

**Comment by andykitch** [comment]
Marianne has provided a dataset - see attachment
[dataverse_files.zip](https://github.com/icipe-official/vectoratlas-software-code/files/9606720/dataverse_files.zip)

**Comment by colin-turner-cg** [comment]
I've noticed in the `species` table that letters with accents (ö, ü etc) have been replaced with the Replacement Character.

Bug https://github.com/icipe-official/vectoratlas-software-code/issues/144 created.

**Comment by colin-turner-cg** [comment]
All AC met:

1) Two tables relating to species exist, `species` and `recorded_species`
2) The `species` has been initialised with the list of species in the attachment.
3) New data links to the existing species table.
