### ISSUE TITLE
Deploy the system to the test environment

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#64]
With the test environment infrastructure deployed, we need to deploy the test environment to that database and virtual machine. This may require changes to the deployment as the database is currently included in the docker compose configuration. 

This only needs to be a manual deployment for now but we should write down all the steps in the deployment section of the SMG. We will automate this in another story.

**Acceptance criteria**:
- [x] The test system can be reached on a public IP version of the url (no domain name needed yet)
- [x] The test system behaves the same as the current local version (i.e. all pages can be reached and the same information is shown).
- [x] The steps of the deployment are documented in the SMG.

**Comment by ray-millward-tessella** [comment]
The domain name registration has already been hooked up so the system is already accessible from http://vectoratlas.icipe.org/

**Comment by ray-millward-tessella** [comment]
@andykitch the callback url for the deployed system doesn't work, presumably because it's still set to localhost. Any idea what the Auth0 callback url needs to be updated to?

**Comment by colin-turner-cg** [comment]
All AC met:
- Test system URL is: https://vectoratlas.icipe.org/map.
- The test system behaves the same as the current local version - home, about, map pages can be reached and have the same information as development environment. I have alse been able to log in and out.
- The steps of the deployment are documented in the SMG (\docs\SMG\08-deployment).
