### ISSUE TITLE
Automate the deployment of the test environment

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#65]
Depends on #64 

With the test environment set up, we now need to automate the deployment of the system. This will likely involve creating a deployment script that can then be run as part of a GitHub build pipeline where the pipeline can ssh into the machine to run the script.

We need to ensure all secrets are held securely for this and only people with sufficient permission can run the deployment pipeline (ideally named members of the team but it may be sufficient to keep it to admins on this project).

**Acceptance Criteria**:
- [x] A script can be run to deploy the system to the test environment
- [x] A GitHub build pipeline exists that can run the deployment
- [x] The deployment pipeline can only be run by a defined subset of people (either named or project admins)

**Comment by colin-turner-cg** [comment]
Deployment instructions can be found here: `docs\SMG\08-deployment.md` and a test added to STS under section 3. Production Deployment Test Script.
