### ISSUE TITLE
Update the source entity to be more generic

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#66]
The entity for managing sources at the moment relies on an `article title` or `journal title` , we need to make this more generic so that it includes a source text field of some sort to handle unpublished field data. It would be good to confirm with Marianne but one suggestion is to include a "citation" field, the plan would then be to include this as a list of citations when users download data.

The ingestion scripts need to be updated to reflect the new source structure.

**Acceptance Criteria**
- [x] The sources entity includes a more generic citation field that can be used to list sources.
- [x] The ingestion system should still be preserved in a separate field (i.e. we can tell an article was ingested from a partner system)
- [ ] Data can be ingested into this new structure.

**Comment by colin-turner-cg** [comment]
Moving this back "In Progress" after speaking with Andy. PRs need to be completed in order for the ingest to work.

**Comment by colin-turner-cg** [comment]
All AC met. Data upload to localhost:1234/vector-api/ingest/uploadBionomics is working.
