### ISSUE TITLE
Add a secured page for creating a new source

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#69]
Add a new blank secured page in the website for creating a new source, again only users with the uploader role should be able to get here. This will also involve creating a new 403 page for the site.

**Acceptance criteria**
- [x] The UI redirects a user that isn't logged in to the login page and then back to the sources page on successful login.
- [x] The UI allows a logged in user to go to the sources page (content is part of a separate story).
- [x] The UI displays a 403 page for a logged in user without the uploader role.

**Comment by andykitch** [comment]
Thought will need to be given as to whether it's best to have this as a separate page or just (for example) a dialog within the sources page

**Comment by colin-turner-cg** [comment]
Tests 5.1 to 5.3 in STS
