### ISSUE TITLE
Investigate what would be needed to run our own tile server

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#7]
The Vector Atlas needs to be able to serve GeoJSON for the outlines of countries in Africa as well as raster layers of maps. We should investigate what we need to do if we were to run our own tile server that serves these items. How much resource does it require to run a tile server and would it work with a low speed connection? There is potentially an acceptance of poorer performance if someone is trying to view maps over a poor connection.

**Acceptance Criteria**
- [ ] Outputs of the investigation are documented here
- [ ] New stories from the outputs have been added to the backlog.

**Comment by ray-millward-tessella** [comment]
I've started looking at possibilities for running a tile server for our maps as well as having layers on top. I've been using [tileserver-gl](https://github.com/maptiler/tileserver-gl) as a docker image and converting our various geojson or geotiff files to the mbtiles format - this seems to be much smaller (it's essentially a self-contained sqlite database) and the tile server generates the png tiles on the fly. I haven't yet worked out if this interfaces with leaflet or not, I would hope so as the tile server provides a standard /{z}/{x}/{y} route.

These are the commands I used:
```
gdaldem color-relief an_gambiae_map.tif colormap.txt an_gambiae_colorized.tif -alpha
gdal_translate -of MBTiles -ot Byte an_gambiae_colorized.tif an_gambiae_map2.mbtiles
gdaladdo -r nearest an_gambiae_map2.mbtiles 2 4 8 16 32
docker run --rm -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl
```
and it gave the result attached.
![image (12)](https://user-images.githubusercontent.com/34268284/180402617-73cb12c3-2d83-43ae-a52b-1e887c0cba16.png)

**Comment by ray-millward-tessella** [comment]
[original_files.zip](https://github.com/icipe-official/vectoratlas-software-code/files/9166257/original_files.zip)
Here's the original tif and the resulting mbtiles files if you want to have a go at running the container (the config will need to be updated to remove the countries-raster.mbtiles file)

**Comment by ray-millward-tessella** [comment]
Leaflet didn't render the geoJSON that was converted to an mbtiles format because it didn't know how to render vector layers - we need to work out how to either render vector layers or convert to a png layer that leaflet can handle.

**Comment by ray-millward-tessella** [comment]
![image (15)](https://user-images.githubusercontent.com/34268284/184128397-90a9850c-9648-4205-9e5e-e06227008e9b.png)

After experimenting with OpenLayers I was able to get it to render vector layers easily as well as applying styling to the vector components.

Data was gathered from Natural Earth. Instructions for building the geoJSON from Natural Earth data:

- Go to natural earth and look for the layers you want, e.g. https://www.naturalearthdata.com/downloads/10m-physical-vectors/ has the land and ocean maps I used
- Download the zip and extract it
- From within the folder run `ogr2ogr -f GeoJSON oceans.json ne_10m_ocean.shp` and it will use the other files in the folder for metadata. (You need to install gdal to have these tools)
- Copy all the json files you want in the map in to a single folder
- From that folder run `tippecanoe -zg -o world.mbtiles --coalesce-densest-as-needed --extend-zooms-if-still-dropping --force *.json` to generate the combined mbtiles file
- Update the tileserver-gl config to reference this file
- This should now come through as different layers in the OpenLayers VectorTileSource and you can tweak the styles based on the name of the layer (note the name of the layer is the name of the geoJSON file that went in)

**Comment by ray-millward-tessella** [comment]
A knowledge sharing session with the Malaria Atlas Project showed that they were using a similar stack but instead of tileserver-gl they were using geoserver https://geoserver.org/ - the main reason for this is that it provides a much richer interface and integration capabilities with external GIS software. This is possibly too heavy-weight for our requirements but we may need to revisit this decision later. For the moment we will use tileserver-gl as it's lighter weight and still servers both vector and raster data as tiles.

One major difference is that geoserver natively supports caching of tiles rather than rendering them on every request. Depending on performance we may want to look to introduce a proxy cache for the tile server in our reverse proxy https://www.nginx.com/blog/nginx-caching-guide/

**Comment by ray-millward-tessella** [comment]
New stories raised in #52 , #53 and #54

**Comment by andykitch** [comment]
Reviewed and approved

**Comment by colin-turner-cg** [comment]
Closing as complete.
