### ISSUE TITLE
Add a form to the sources page for adding a new source

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#70]
Add a form to the sources page for creating a new source - this will likely involve introducing a form library of some sort (possibly react hook form given support for formik is stopping). 

There should be validation on the various fields not being blank. The system should also validate that the exact same source doesn't already exist (with a backoff so this is not on every key stroke) - this will need an API call to the backend.

When the form is submitted, the API should generate an ID to record against the source and the form should display a success message with that ID and then blank the form on a successful submission (but not if it fails).

**Acceptance Criteria**
- [x] An uploader can submit a valid source and see the ID of the newly created source.
- [x] An uploader can't submit a new source if any fields are blank
- [x] An uploader can't submit a new source if the source matches an existing one.
- [x] The page shows the ID of a new source and blanks the fields if source creation is successful.
- [x] The page shows the error and leaves the fields as they are if there is an error.

**Comment by colin-turner-cg** [comment]
This issue still persists but is more harder to replicate now. It occurs very intermittently and seems to only occur if the drawer is collapsed at a point where the map is loading in data.

**Comment by colin-turner-cg** [comment]
Tests TC-5.5 to TC-5.8 added to STS
