### ISSUE TITLE
Update the docker environment so the config files are mounted from a volume

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#71]
Currently we have various config files for feature flags and map styles in the API - these are built into the image at the moment but should actually be configurable at run time. We need to modify the environment so it mounts an assets folder in the API that can be modified without having to rebuild the environment.

This will likely also involve updating the config load so it watches the files somehow rather than loading them once at the start or on every call.

**Acceptance criteria**:
- [x] Configuration for the feature flags and map styles can be modified whilst the docker-compose environment is running without rebuilding the environment.

**Comment by colin-turner-cg** [comment]
Setting the map feature flag to `false` disables the map link on the homepage and removes the interactive map from the map page. A map image is still visible on the homepage that links to the map page (the interactive map is not visible), should this map image also be removed? @ray-millward-tessella

**Comment by colin-turner-cg** [comment]
AC met, see tests TC-1.7 to TC-1.10 in STS.
