### ISSUE TITLE
Update the contents of the ADD

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#72]
Now that we have a clearer idea of what the system will look like, we need to fill in the contents of the ADD. Add descriptions for all the sections and include images with the source files for future modification.

**Acceptance criteria**
- [x] The ADD contains information describing the various aspects of the system.
- [x] Diagrams are included along with the source files for modifying them later.
- [x] There should not be any template material left that needs filling in unless there is still an architectural decision that needs making.

**Comment by ray-millward-tessella** [comment]
@andykitch can you confirm here that you reviewed the updated contents of the ADD as part of a PR. It can then be moved to testing.

**Comment by andykitch** [comment]
Confirmed

**Comment by colin-turner-cg** [comment]
Some of the pages are missing sections:

01-architecture-overview
Architecture Decision Records - file linked doesn't exist
References - incomplete
Architectural Styles states "Examples listed: update for your system" - does this need updating?

02-architecture-context
Environmental constraints - not linked to anything

03-architecture-functional
Has a link to "Significant area 1", incomplete links to other sections

04-architecture-process
No content for:
	Processing pipelines
	State models
	Streaming components
	Avoiding 2-Phase Commit
	Related sections

05-architecture-security
No content for:
	Command security
	Related sections
Authentication and Authorization has a "TODO" comment

06-architecture-deployment
No content for:
	Related sections
	
07-architecture-development
No content for:
	Design and Build Process
	Related sections

08-architecture-testing
No content for:	
	Test services
	Related sections

**Comment by ray-millward-tessella** [comment]
The links are now fixed in the latest version.
