### ISSUE TITLE
Update the zoom controls and attribution for the map.

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#73]
Update the zoom controls on the map to use the default ones and place the attribution in the bottom right. The attribution should reference the Natural Earth site using the text from here https://www.naturalearthdata.com/about/terms-of-use/ "Made with Natural Earth"

**Acceptance criteria**:
- [x] Zoom controls appear in the top left with a similar style to the operlayers example.
- [x] Natural Earth is attributed in the bottom right.

**Comment by colin-turner-cg** [comment]
All AC met.
