### ISSUE TITLE
Add a filters and layers component to the map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#74]
Users need to be able to filter the data and turn model output layers on and off on the map. We should add a new filters and layers component that is largely empty for now - it should just query the available layers from the API and display them in this component with the ability to turn them on and off (no impact on the map yet).

The original workshop had a screen that looked like this:
![image](https://user-images.githubusercontent.com/34268284/188174176-664fc611-b8f5-4ead-a86d-5baaa2c45e59.png)

but it may be better to use a draw (https://mui.com/material-ui/react-drawer/) as this would give us an independent control to develop and update the map state with.

**Acceptance crtieria**
- [x] A list of overlays can be queried from the server, this should provide enough information to use in the map view (e.g. the name of the layer to query from the tile server as well as a display name, maybe other properties).
- [x] The map displays an expandable filter and overlay area.
- [x] The overlay area shows a list of overlays that can be turned on and off.

**Comment by colin-turner-cg** [comment]
All AC met:
An API call returns a list of map overlays (TC-3.10)
An expandable section containing overlays and map filter options can be seen (TC-3.11)
A list of overlays exist that can be turned on or off (TC-3.11)
