### ISSUE TITLE
Load overlay maps in the tileserver

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#75]
[an_gambiae_map.zip](https://github.com/icipe-official/vectoratlas-software-code/files/9478888/an_gambiae_map.zip)
Use the example map here to build a script that converts a tif into an mbtiles file using the output from #7 

This mbtiles file should be loaded with the tile server manually for now and we should use lessons learnt from this story to generate a new one about updating the config file automatically. The idea being eventually that a modeller might upload a tif file and then the system will automatically generate the mbtiles file and update the config. This may be a step too far and it may be a support process to update the maps but we won't know till after this story.

The list of maps returned by the API also needs to be updated, this depends on #74 

**Acceptance criteria**:
- [x] model output tif files can be converted to mbtiles files
- [x] model outputs can be served as layers from the tile server
- [x] the API returns the correct list of layers based on what is served from the tile server.

**Comment by colin-turner-cg** [comment]
All AC met.

I have successfully converted a sample model tif file to an mbtiles file (an_gambiae_map.tif to an_gambiae_map.mbtiles).
A `GET` request made to `http://localhost:1234/vector-api/config/tile-server-overlays` will return the layers.
