### ISSUE TITLE
Set up a new Architectural Design Document with Architectural Decision Records

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#8]
Create a new documents folder in the code repo and add a new Architectural Design Document (ADD) and begin filling in content. It doesn't need to be complete at this stage, only high level information about the project and architecture.

Also add a folder and start recording Architectural Decision Records (ADRs) to document why we've made certain choices.

**Acceptance Criteria**

- [x] An ADD exists in the code base with a high level outline of the project.
- [x] An ADR folder exists with at least one ADR covering the decision to use ADRs.

**Comment by colin-turner-cg** [comment]
ADD exists in the folder docs/architecture/description and contains a high level overview of system architecture.
ADR folder exists (docs/architecture/ADRs) and contains one ADR,
