### ISSUE TITLE
Add a System Maintenance Guide

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#9]
Add an SMG to the documents folder, it only needs to be an initial document with the general page structure. The main part will be to start writing about how to set up a development environment.

**Acceptance Criteria**

- [x] A new SMG exists in the documents folder in the code base.
- [x] There are details in the SMG about how to set up a development environment.

**Comment by Christopher-Sandbach** [comment]
Added a small section in the SMG, under 03, pointing to the tile server script page so local data can be initialised

**Comment by colin-turner-cg** [comment]
All acceptance criteria met.

An SMG document is saved in the code base at:  docs\SMG. It contains full details about how to set up a development environment and will continue to evolve as the project progresses.
