### ISSUE TITLE
Add an API route to load occurrence data for the map 

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#98]
It needs to be possible to get occurrence data from the graphql API endpoint, using an appropriate query. The initial fields we care about are:
- site.location
- sample.n_all
These two fields should give us enough information to start plotting on the map. The query used should initially just extract these fields.
Editing the occurrence.resolver class is a good starting point. To populate your db, use the occurrence.csv template file in the API public folder.

Acceptance Criteria:
- [x] It is possible to extract the above data from a populated db, through the `vector-api/graphql` endpoint, using an appropriate query
- [x] The query is able to get paginated data
- [x] The query is documented on this story

**Comment by Christopher-Sandbach** [comment]
Extending the test/get_nested branch, sample export added to resolver with queries tested on 'http://localhost:1234/vector-api/graphql' using a POST from Postman:

**site location/co-ordinates can now be queried:** 

query {
  allGeoData{
     site{
         longitude,
         latitude
        }
      }
  }


**sample n_all can now be queried:**

```
query {
  allGeoData{
     sample{
         n_all
        }
      }
  }
```

**Comment by colin-turner-cg** [comment]
All AC met, test TC-3.7 created in STS.
