### ISSUE TITLE
Load occurrence data on map

### ISSUE THREAD

**Issue by ray-millward-tessella** [icipe-official/vectoratlas-software-code#99]
Markers need to be added to the map for occurrence data - specifically location and count (site.location and sample.n_all). The markers and data display for this should follow the documented design from #127 (if this has been completed first - otherwise just add markers with hoverover data for the count)
Data should be extracted from the graphql endpoint, using the query documented in #98.
Data should be extracted in pages - loading an appropriate number of data points initially, and subsequently loading additional data until all data is loaded. This is to reduce the initial load time of the page.

Acceptance Criteria:
- [x] Occurrence data is show on the map
- [x] This data is loaded in pages  loading an appropriate number of data points initially, and subsequently loading additional data until all data is loaded. The map is populated with more data after each load.
- [x] The location and count data is shown in a clear way

**Comment by colin-turner-cg** [comment]
All AC met.
1) Occurrence data points, showing location and count, can be seen on the map (TC-3.12).
2) The data loads in chunks of 100. Examples of calls to API: 
`query: "query Occurrence {\n OccurrenceData(skip:0, take:100)\n {\n items{\n year_start\n site{\n location\n }\n sample{\n n_all\n }\n }\n total\n hasMore\n }\n }"`
`query: "query Occurrence {\n OccurrenceData(skip:900, take:100)\n {\n items{\n year_start\n site{\n location\n }\n sample{\n n_all\n }\n }\n total\n hasMore\n }\n }"`
